platform :ios, "8.0"
use_frameworks!

target 'Fit Life' do

pod 'Alamofire', '~> 3.0'
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

end

target 'Fit LifeTests' do

end

target 'Fit LifeUITests' do

end

